print("Running Make Account Test: ")
exec(open("makeAccount.py").read(), globals())
print("Running Login Test: ")
exec(open("login.py").read(), globals())
print("Running Logout Test: ")
exec(open("logout.py").read(), globals())
print("Running Cheapest Laptop Test: ")
exec(open("cheapestLaptop.py").read(), globals())
print("Running Change Address Test: ")
exec(open("changeAddress.py").read(), globals())
print("Running Similar Searches Test: ")
exec(open("similarSearches.py").read(), globals())
